// src/components/LocationForm/LocationForm.tsx
import React, { useState, useCallback, useRef } from 'react';
import { LocationFormData, LocationType } from '../../core/entities/Location';
import { LocationCodeGenerator } from '../../utils/LocationCodeGenerator';

interface LocationFormProps {
    initialData?: Partial<LocationFormData>;
    onSubmit: (data: LocationFormData) => Promise<{ success: boolean; errors?: Record<string, string> }>;
    onCancel: () => void;
    isSubmitting?: boolean;
    title?: string;
    mode?: 'add' | 'edit';
    existingLocations?: Array<{ code?: string }>;
}

export const LocationForm: React.FC<LocationFormProps> = ({
    initialData,
    onSubmit,
    onCancel,
    isSubmitting = false,
    title = 'Add Location',
    mode = 'add',
    existingLocations = []
}) => {
    // Default form data with proper typing
    const defaultFormData: LocationFormData = {
        name: '',
        type: 'hub',
        status: 'active',
        address: '',
        city: '',
        country: 'South Africa',
        maxAssets: 100,
        totalAssets: 0,
        code: '', // Ensure code is always a string, not undefined
        contactName: '',
        contactEmail: '',
        contactPhone: '',
        description: '',
        region: '',
        managerId: ''
    };

    // Initialize form state
    const [formData, setFormData] = useState<LocationFormData>(() => ({
        ...defaultFormData,
        ...initialData
    }));

    const [errors, setErrors] = useState<Record<string, string>>({});
    const [isAutoGenerated, setIsAutoGenerated] = useState<boolean>(!initialData?.code);
    const previousNameRef = useRef<string>(formData.name);
    const previousTypeRef = useRef<LocationType>(formData.type);

    // Handle name change with immediate code generation
    const handleNameChange = useCallback((value: string) => {
        // Auto-generate code immediately if conditions are met
        if (mode === 'add' && isAutoGenerated && value && formData.type) {
            const generatedCode = LocationCodeGenerator.generate(
                value,
                formData.type,
                existingLocations
            );

            if (generatedCode && generatedCode !== formData.code) {
                setFormData(prev => ({ ...prev, name: value, code: generatedCode }));
            } else {
                setFormData(prev => ({ ...prev, name: value }));
            }
        } else {
            setFormData(prev => ({ ...prev, name: value }));
        }

        // Clear error for this field if it exists
        if (errors.name) {
            setErrors(prev => ({ ...prev, name: '' }));
        }

        // Update ref
        previousNameRef.current = value;
    }, [formData.type, formData.code, mode, isAutoGenerated, existingLocations, errors.name]);

    // Handle type change with immediate code generation
    const handleTypeChange = useCallback((value: LocationType) => {
        // Auto-generate code immediately if conditions are met
        if (mode === 'add' && isAutoGenerated && formData.name && value) {
            const generatedCode = LocationCodeGenerator.generate(
                formData.name,
                value,
                existingLocations
            );

            if (generatedCode && generatedCode !== formData.code) {
                setFormData(prev => ({ ...prev, type: value, code: generatedCode }));
            } else {
                setFormData(prev => ({ ...prev, type: value }));
            }
        } else {
            setFormData(prev => ({ ...prev, type: value }));
        }

        // Clear error for this field if it exists
        if (errors.type) {
            setErrors(prev => ({ ...prev, type: '' }));
        }

        // Update ref
        previousTypeRef.current = value;
    }, [formData.name, formData.code, mode, isAutoGenerated, existingLocations, errors.type]);

    const handleChange = useCallback((field: keyof LocationFormData, value: string | number) => {
        // Prevent manual editing of auto-generated code
        if (field === 'code' && mode === 'add' && isAutoGenerated) {
            return;
        }

        setFormData(prev => {
            const newFormData = { ...prev, [field]: value };
            return newFormData;
        });

        // If manually editing code, mark as not auto-generated
        if (field === 'code' && value !== formData.code) {
            setIsAutoGenerated(false);
        }

        // Clear error for this field if it exists
        if (errors[field]) {
            setErrors(prev => ({ ...prev, [field]: '' }));
        }
    }, [mode, isAutoGenerated, formData.code, errors]);

    const handleAutoGenerate = useCallback(() => {
        if (formData.name && formData.type) {
            const generatedCode = LocationCodeGenerator.generate(
                formData.name,
                formData.type,
                existingLocations
            );
            if (generatedCode) {
                setFormData(prev => ({ ...prev, code: generatedCode }));
                setIsAutoGenerated(true);
            }
        }
    }, [formData.name, formData.type, existingLocations]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setErrors({});

        // Validate required fields
        const validationErrors: Record<string, string> = {};

        if (!formData.name.trim()) {
            validationErrors.name = 'Location name is required';
        }

        // Now formData.code is guaranteed to be a string (not undefined)
        const code = formData.code || '';
        if (!code.trim()) {
            validationErrors.code = 'Location code is required';
        } else if (!LocationCodeGenerator.isValid(code)) {
            validationErrors.code = 'Invalid location code format (e.g., HUB-JHB-001)';
        }

        if (Object.keys(validationErrors).length > 0) {
            setErrors(validationErrors);
            return;
        }

        try {
            const result = await onSubmit(formData);
            if (!result.success && result.errors) {
                setErrors(result.errors);
            }
        } catch {
            setErrors({ general: 'Failed to submit form. Please try again.' });
        }
    };


    const getLocationSuggestions = useCallback(() => {
        if (!formData.name) return [];

        const suggestions = [];
        const normalizedName = formData.name.toLowerCase();
        try {
            const locationCodes = LocationCodeGenerator.getLocationCodes?.();
            if (!locationCodes) return [];

            for (const [key, code] of Object.entries(locationCodes)) {
                if (typeof key === 'string' && typeof code === 'string') {
                    if (key.includes(normalizedName) || normalizedName.includes(key)) {
                        suggestions.push(`${code} - ${key.charAt(0).toUpperCase() + key.slice(1)}`);
                    }
                }
            }
        } catch {
            return [];
        }

        return suggestions.slice(0, 3);
    }, [formData.name]);

    const locationSuggestions = getLocationSuggestions();

    return (
        <form onSubmit={handleSubmit} className="location-form">
            {/* General error */}
            {errors.general && (
                <div className="error-message">
                    <span className="material-icons">error</span>
                    <span>{errors.general}</span>
                </div>
            )}

            {/* Name field */}
            <div className="form-group">
                <label htmlFor="name">Location Name *</label>
                <input
                    id="name"
                    type="text"
                    value={formData.name}
                    onChange={(e) => handleNameChange(e.target.value)}
                    className={errors.name ? 'error' : ''}
                    disabled={isSubmitting}
                    placeholder="e.g., Johannesburg Hub"
                />
                {errors.name && <span className="error-text">{errors.name}</span>}

                {/* Location suggestions */}
                {locationSuggestions.length > 0 && mode === 'add' && (
                    <div className="field-suggestions">
                        <span className="suggestion-label">Common locations:</span>
                        {locationSuggestions.map((suggestion, index) => (
                            <span key={index} className="suggestion-chip">
                                {suggestion}
                            </span>
                        ))}
                    </div>
                )}
            </div>

            {/* Type field */}
            <div className="form-group">
                <label htmlFor="type">Type *</label>
                <select
                    id="type"
                    value={formData.type}
                    onChange={(e) => handleTypeChange(e.target.value as LocationType)}
                    className={errors.type ? 'error' : ''}
                    disabled={isSubmitting}
                >
                    <option value="hq">Headquarters (HQ)</option>
                    <option value="hub">Hub</option>
                    <option value="site">Site</option>
                    <option value="branch">Branch</option>
                    <option value="other">Other</option>
                </select>
                {errors.type && <span className="error-text">{errors.type}</span>}
            </div>

            {/* Code field with auto-generation */}
            <div className="form-group">
                <label htmlFor="code">Location Code *</label>
                <div className="code-input-container">
                    <input
                        id="code"
                        type="text"
                        value={formData.code}
                        onChange={(e) => handleChange('code', e.target.value)}
                        className={`${errors.code ? 'error' : ''} ${mode === 'add' && isAutoGenerated ? 'readonly-input' : ''}`}
                        disabled={isSubmitting || (mode === 'add' && isAutoGenerated)}
                        placeholder="e.g., HUB-JHB-001"
                    />
                    {mode === 'add' && (
                        <button
                            type="button"
                            onClick={handleAutoGenerate}
                            className="btn-generate"
                            disabled={!formData.name || !formData.type || isSubmitting}
                        >
                            <span className="material-icons">autorenew</span>
                            Auto-generate
                        </button>
                    )}
                </div>
                {errors.code && <span className="error-text">{errors.code}</span>}

                {/* Code format hint */}
                <div className="field-hint">
                    {mode === 'add' ? (
                        isAutoGenerated ? (
                            <span className="hint-success">
                                <span className="material-icons">check_circle</span>
                                Auto-generated code: {formData.code || 'Enter name and type first'}
                            </span>
                        ) : (
                            'Format: TYPE-LOC-001 (e.g., HUB-JHB-001)'
                        )
                    ) : (
                        'Edit only if necessary'
                    )}
                </div>
            </div>

            {/* Status field */}
            <div className="form-group">
                <label htmlFor="status">Status *</label>
                <select
                    id="status"
                    value={formData.status}
                    onChange={(e) => handleChange('status', e.target.value)}
                    className={errors.status ? 'error' : ''}
                    disabled={isSubmitting}
                >
                    <option value="active">Active</option>
                    <option value="maintenance">Maintenance</option>
                    <option value="offline">Offline</option>
                </select>
                {errors.status && <span className="error-text">{errors.status}</span>}
            </div>

            {/* Address field */}
            <div className="form-group">
                <label htmlFor="address">Address</label>
                <input
                    id="address"
                    type="text"
                    value={formData.address || ''}
                    onChange={(e) => handleChange('address', e.target.value)}
                    className={errors.address ? 'error' : ''}
                    disabled={isSubmitting}
                    placeholder="Enter full address"
                />
                {errors.address && <span className="error-text">{errors.address}</span>}
            </div>

            {/* City and Country */}
            <div className="form-row">
                <div className="form-group">
                    <label htmlFor="city">City</label>
                    <input
                        id="city"
                        type="text"
                        value={formData.city || ''}
                        onChange={(e) => handleChange('city', e.target.value)}
                        className={errors.city ? 'error' : ''}
                        disabled={isSubmitting}
                        placeholder="Enter city"
                    />
                    {errors.city && <span className="error-text">{errors.city}</span>}
                </div>

                <div className="form-group">
                    <label htmlFor="country">Country</label>
                    <input
                        id="country"
                        type="text"
                        value={formData.country || ''}
                        onChange={(e) => handleChange('country', e.target.value)}
                        className={errors.country ? 'error' : ''}
                        disabled={isSubmitting}
                        placeholder="Enter country"
                    />
                    {errors.country && <span className="error-text">{errors.country}</span>}
                </div>
            </div>

            {/* Capacity fields */}
            <div className="form-row">
                <div className="form-group">
                    <label htmlFor="maxAssets">Max Assets</label>
                    <input
                        id="maxAssets"
                        type="number"
                        value={formData.maxAssets || 0}
                        onChange={(e) => handleChange('maxAssets', parseInt(e.target.value) || 0)}
                        className={errors.maxAssets ? 'error' : ''}
                        disabled={isSubmitting}
                        min="0"
                    />
                    {errors.maxAssets && <span className="error-text">{errors.maxAssets}</span>}
                </div>

                <div className="form-group">
                    <label htmlFor="totalAssets">Current Assets</label>
                    <input
                        id="totalAssets"
                        type="number"
                        value={formData.totalAssets || 0}
                        onChange={(e) => handleChange('totalAssets', parseInt(e.target.value) || 0)}
                        className={errors.totalAssets ? 'error' : ''}
                        disabled={isSubmitting}
                        min="0"
                        max={formData.maxAssets}
                    />
                    {errors.totalAssets && <span className="error-text">{errors.totalAssets}</span>}
                    <div className="field-hint">
                        Must be less than or equal to Max Assets
                    </div>
                </div>
            </div>

            {/* Region field */}
            <div className="form-group">
                <label htmlFor="region">Region/Province</label>
                <select
                    id="region"
                    value={formData.region || ''}
                    onChange={(e) => handleChange('region', e.target.value)}
                    className={errors.region ? 'error' : ''}
                    disabled={isSubmitting}
                >
                    <option value="">Select Region</option>
                    <option value="Gauteng">Gauteng</option>
                    <option value="Western Cape">Western Cape</option>
                    <option value="KwaZulu-Natal">KwaZulu-Natal</option>
                    <option value="Eastern Cape">Eastern Cape</option>
                    <option value="Limpopo">Limpopo</option>
                    <option value="Mpumalanga">Mpumalanga</option>
                    <option value="North West">North West</option>
                    <option value="Free State">Free State</option>
                    <option value="Northern Cape">Northern Cape</option>
                </select>
                {errors.region && <span className="error-text">{errors.region}</span>}
            </div>

            {/* Description */}
            <div className="form-group">
                <label htmlFor="description">Description</label>
                <textarea
                    id="description"
                    value={formData.description || ''}
                    onChange={(e) => handleChange('description', e.target.value)}
                    className={errors.description ? 'error' : ''}
                    disabled={isSubmitting}
                    placeholder="Add description or notes about this location"
                    rows={2}
                />
                {errors.description && <span className="error-text">{errors.description}</span>}
            </div>

            {/* Contact Information */}
            <div className="form-section">
                <h4 className="section-title">Contact Information</h4>
                <div className="form-grid">
                    <div className="form-group">
                        <label htmlFor="contactName">Contact Name</label>
                        <input
                            id="contactName"
                            type="text"
                            value={formData.contactName || ''}
                            onChange={(e) => handleChange('contactName', e.target.value)}
                            disabled={isSubmitting}
                            placeholder="Contact person name"
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="contactEmail">Contact Email</label>
                        <input
                            id="contactEmail"
                            type="email"
                            value={formData.contactEmail || ''}
                            onChange={(e) => handleChange('contactEmail', e.target.value)}
                            disabled={isSubmitting}
                            placeholder="contact@example.com"
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="contactPhone">Contact Phone</label>
                        <input
                            id="contactPhone"
                            type="tel"
                            value={formData.contactPhone || ''}
                            onChange={(e) => handleChange('contactPhone', e.target.value)}
                            disabled={isSubmitting}
                            placeholder="+27 12 345 6789"
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="managerId">Manager ID</label>
                        <input
                            id="managerId"
                            type="text"
                            value={formData.managerId || ''}
                            onChange={(e) => handleChange('managerId', e.target.value)}
                            disabled={isSubmitting}
                            placeholder="Manager user ID"
                        />
                    </div>
                </div>
            </div>

            {/* Form Actions */}
            <div className="form-actions">
                <button
                    type="button"
                    onClick={onCancel}
                    disabled={isSubmitting}
                    className="btn-secondary"
                >
                    <span className="material-icons">cancel</span>
                    Cancel
                </button>
                <button
                    type="submit"
                    disabled={isSubmitting}
                    className="btn-primary"
                >
                    {isSubmitting ? (
                        <>
                            <span className="material-icons spinner">refresh</span>
                            Saving...
                        </>
                    ) : (
                        <>
                            <span className="material-icons">save</span>
                            {title}
                        </>
                    )}
                </button>
            </div>
        </form>
    );
};